### ISSUE TITLE
tarpc client occasionally panics during multiple in-flight requests

### ISSUE THREAD

**Issue by d1vyank** [google/tarpc#220]
**Environment information**
```
# Relevant Cargo.toml section
bincode-transport = { package = "tarpc-bincode-transport", version = "0.4"}
futures-preview = { version = "0.3.0-alpha.13", features = ["compat"] }
tarpc = { version = "0.15.0", features = ["serde1"] }
tokio = { version = "0.1", features = ["async-await-preview"] }
tokio-executor = "0.1"
tokio-async-await = "0.1.6"
protobuf = {git= "https://github.com/stepancheg/rust-protobuf", features= ["with-serde"]}
```
```shell
$ rustc --version
rustc 1.35.0-nightly (82e2f3ec2 2019-03-20)
```

**Description**

tarpc client panics with message :
```thread 'tokio-runtime-worker-7' panicked at 'Receiver::next_message called after 'None'', src/libcore/option.rs:1034:5```

originating in tarpc/rpc/src/client/channel.rs:
```
  14:     0x559a441ab98d - <tarpc_lib::client::channel::CanceledRequests as futures_core::stream::Stream>::poll_next::ha00263c4bd53c703
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:624
  15:     0x559a44196b22 - <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next::h636d07e1ea0b4220
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.13/src/stream/mod.rs:83
  16:     0x559a441923c4 - futures_util::stream::StreamExt::poll_next_unpin::h6b39e67ee2142875
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/stream/mod.rs:1053
  17:     0x559a44124063 - tarpc_lib::client::channel::RequestDispatch<Req,Resp,C>::poll_next_cancellation::h0bc50f1ff7a1097d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:426
  18:     0x559a44121c50 - tarpc_lib::client::channel::RequestDispatch<Req,Resp,C>::pump_write::h35740a975ee1227d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:348
  19:     0x559a4411e180 - <tarpc_lib::client::channel::RequestDispatch<Req,Resp,C> as core::future::future::Future>::poll::h7028333b56cb50b1
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:536
```

<details><summary>click for full stack trace</summary><p>

```
thread 'tokio-runtime-worker-7' panicked at 'Receiver::next_message called after 'None'', src/libcore/option.rs:1034:5
   0:     0x559a447197d3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h5a00e69bd84d3d41
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x559a44714aeb - std::sys_common::backtrace::_print::h1cf32af908d9a358
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x559a447179c6 - std::panicking::default_hook::{{closure}}::h4ca90b153259a6bd
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x559a44717759 - std::panicking::default_hook::h27ba530872f2e28e
                               at src/libstd/panicking.rs:211
   4:     0x559a447180cf - std::panicking::rust_panic_with_hook::hb6cfbd8cab6d00a1
                               at src/libstd/panicking.rs:474
   5:     0x559a44717c51 - std::panicking::continue_panic_fmt::h21a316405327475f
                               at src/libstd/panicking.rs:381
   6:     0x559a44717b35 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x559a4472fa7c - core::panicking::panic_fmt::h479b52b4b16823c9
                               at src/libcore/panicking.rs:85
   8:     0x559a4472fae6 - core::option::expect_failed::he723cf53a64b9307
                               at src/libcore/option.rs:1034
   9:     0x559a441af7ac - core::option::Option<T>::expect::h8b504c207f59a9cf
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libcore/option.rs:312
  10:     0x559a441a9a16 - futures_channel::mpsc::Receiver<T>::next_message::h0c5d3653d58e9199
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-preview-0.3.0-alpha.13/src/mpsc/mod.rs:840
  11:     0x559a441aa5ee - <futures_channel::mpsc::Receiver<T> as futures_core::stream::Stream>::poll_next::h8fcdc8e350857710
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-preview-0.3.0-alpha.13/src/mpsc/mod.rs:910
  12:     0x559a441aa965 - <futures_channel::mpsc::UnboundedReceiver<T> as futures_core::stream::Stream>::poll_next::hbdd9bb7fc0d87499
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-channel-preview-0.3.0-alpha.13/src/mpsc/mod.rs:976
  13:     0x559a441a9705 - futures_util::stream::StreamExt::poll_next_unpin::hb0d73876861eec80
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/stream/mod.rs:1053
  14:     0x559a441ab98d - <tarpc_lib::client::channel::CanceledRequests as futures_core::stream::Stream>::poll_next::ha00263c4bd53c703
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:624
  15:     0x559a44196b22 - <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next::h636d07e1ea0b4220
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.13/src/stream/mod.rs:83
  16:     0x559a441923c4 - futures_util::stream::StreamExt::poll_next_unpin::h6b39e67ee2142875
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/stream/mod.rs:1053
  17:     0x559a44124063 - tarpc_lib::client::channel::RequestDispatch<Req,Resp,C>::poll_next_cancellation::h0bc50f1ff7a1097d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:426
  18:     0x559a44121c50 - tarpc_lib::client::channel::RequestDispatch<Req,Resp,C>::pump_write::h35740a975ee1227d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:348
  19:     0x559a4411e180 - <tarpc_lib::client::channel::RequestDispatch<Req,Resp,C> as core::future::future::Future>::poll::h7028333b56cb50b1
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tarpc-lib-0.3.0/src/client/channel.rs:536
  20:     0x559a4411f623 - <F as futures_core::future::TryFuture>::try_poll::h5870ca8c0507f030
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.13/src/future/mod.rs:86
  21:     0x559a4410961e - <futures_util::try_future::unwrap_or_else::UnwrapOrElse<Fut,F> as core::future::future::Future>::poll::h9e47e9a22b9e7137
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/try_future/unwrap_or_else.rs:43
  22:     0x559a4411b544 - futures_core::future::future_obj::if_std::<impl futures_core::future::future_obj::UnsafeFutureObj<T> for alloc::boxed::Box<F>>::poll::hcfcceaf1dfb6872d
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.13/src/future/future_obj.rs:203
  23:     0x559a444bf58f - <futures_core::future::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll::h7ddcfc523027fd4c
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.13/src/future/future_obj.rs:66
  24:     0x559a444bf50d - <futures_core::future::future_obj::FutureObj<T> as core::future::future::Future>::poll::hc5fa08e33c498b6b
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.13/src/future/future_obj.rs:118
  25:     0x559a44040eec - <futures_util::future::unit_error::UnitError<Fut> as core::future::future::Future>::poll::h5e1dfaefd32c0860
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/future/unit_error.rs:36
  26:     0x559a44040fec - <F as futures_core::future::TryFuture>::try_poll::h83c05c4952e4ce80
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-preview-0.3.0-alpha.13/src/future/mod.rs:86
  27:     0x559a440309ac - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::{{closure}}::h5c168f7a2bde2804
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/compat/compat03as01.rs:69
  28:     0x559a4403002c - futures_util::compat::compat03as01::with_context::hc08fe399dfa611ab
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/compat/compat03as01.rs:171
  29:     0x559a440308a2 - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::h4af1f9ffc4088d69
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-preview-0.3.0-alpha.13/src/compat/compat03as01.rs:69
  30:     0x559a444d0f74 - <alloc::boxed::Box<F> as futures::future::Future>::poll::hd109e8188dba89a1
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/future/mod.rs:113
  31:     0x559a4421ccc3 - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::hd69302a229b659d3
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  32:     0x559a4421cf40 - futures::task_impl::Spawn<T>::enter::{{closure}}::h8e27b92cb2e9b696
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  33:     0x559a44248b76 - futures::task_impl::std::set::h3f717cbcfb980e19
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/std/mod.rs:78
  34:     0x559a4421cdbe - futures::task_impl::Spawn<T>::enter::h54d783448b16370b
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:399
  35:     0x559a4421ca77 - futures::task_impl::Spawn<T>::poll_fn_notify::h540a970031f983c3
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:291
  36:     0x559a4421cc27 - futures::task_impl::Spawn<T>::poll_future_notify::h97fbccbf68ad5017
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.26/src/task_impl/mod.rs:329
  37:     0x559a44226851 - tokio_threadpool::task::Task::run::{{closure}}::hf0d8653e389472b4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/task/mod.rs:145
  38:     0x559a44230708 - core::ops::function::FnOnce::call_once::he51d721ec733ddba
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libcore/ops/function.rs:231
  39:     0x559a4421baf8 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h4d74e7fee0b91791
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panic.rs:309
  40:     0x559a4421c7b2 - std::panicking::try::do_call::h15e6cbee82a647bd
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panicking.rs:293
  41:     0x559a4471c3f9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  42:     0x559a4421c56f - std::panicking::try::h3d07305c45e7c804
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panicking.rs:272
  43:     0x559a4421c4e0 - std::panic::catch_unwind::h95d52dc93615849f
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panic.rs:388
  44:     0x559a442262d5 - tokio_threadpool::task::Task::run::h7e9e58fb77fd33d4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/task/mod.rs:130
  45:     0x559a4423d36e - tokio_threadpool::worker::Worker::run_task2::hb19622d364465d16
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:567
  46:     0x559a4423cc33 - tokio_threadpool::worker::Worker::run_task::he04aae796b34f6a6
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:459
  47:     0x559a4423c2b2 - tokio_threadpool::worker::Worker::try_run_owned_task::h905440b076cf7086
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:390
  48:     0x559a4423bcec - tokio_threadpool::worker::Worker::try_run_task::h39968d0c1e73cd67
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:297
  49:     0x559a4423bb45 - tokio_threadpool::worker::Worker::run::h1f54efc011ff1b6e
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:241
  50:     0x559a441b91f1 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h3619a3a2221c5136
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:349
  51:     0x559a441b728b - tokio_trace_core::dispatcher::with_default::h6571e08f96ded27a
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-trace-core-0.1.0/src/dispatcher.rs:54
  52:     0x559a441b922c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hb40fc3460017f136
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:348
  53:     0x559a441bb344 - tokio_timer::timer::handle::with_default::{{closure}}::h17b9863eeefca3f9
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:94
  54:     0x559a441ba2a6 - std::thread::local::LocalKey<T>::try_with::he91f8118ef5a19d9
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:299
  55:     0x559a441b953b - std::thread::local::LocalKey<T>::with::h5b081d328c0b3031
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:245
  56:     0x559a441bb181 - tokio_timer::timer::handle::with_default::h6f9279c87ccd730b
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/timer/handle.rs:81
  57:     0x559a441b9297 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::{{closure}}::h7d03a3d8b678435c
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:347
  58:     0x559a441c4b99 - tokio_timer::clock::clock::with_default::{{closure}}::h229c66c3a0be6090
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:141
  59:     0x559a441ba51a - std::thread::local::LocalKey<T>::try_with::hf01276295b52a67d
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:299
  60:     0x559a441b95bc - std::thread::local::LocalKey<T>::with::hdf20ea16d7dd973e
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:245
  61:     0x559a441c4a89 - tokio_timer::clock::clock::with_default::h232b00caf0f85e82
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.10/src/clock/clock.rs:124
  62:     0x559a441b92e3 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::{{closure}}::hceaa67c49666f4d8
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:346
  63:     0x559a441ba82a - tokio_reactor::with_default::{{closure}}::h016fb0495349fba2
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:237
  64:     0x559a441ba04e - std::thread::local::LocalKey<T>::try_with::he4fde67d22899f84
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:299
  65:     0x559a441b963c - std::thread::local::LocalKey<T>::with::he8178d47d3dc8a49
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:245
  66:     0x559a441ba5e0 - tokio_reactor::with_default::ha238eec3ecf4a201
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.9/src/lib.rs:217
  67:     0x559a441b938b - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::hd022d0f902314d66
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.1.18/src/runtime/threadpool/builder.rs:345
  68:     0x559a44225422 - tokio_threadpool::callback::Callback::call::h0f6fe4f19fc3e7b4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/callback.rs:22
  69:     0x559a4423b7ce - tokio_threadpool::worker::Worker::do_run::{{closure}}::{{closure}}::hd80871b65eea5a85
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:127
  70:     0x559a4423eb7a - tokio_executor::global::with_default::{{closure}}::hc74c137bbfd3b4c4
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:209
  71:     0x559a4424082e - std::thread::local::LocalKey<T>::try_with::hc0b5727fc9a25af6
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:299
  72:     0x559a4423f862 - std::thread::local::LocalKey<T>::with::h448484255db29166
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:245
  73:     0x559a4423ea55 - tokio_executor::global::with_default::hbcc6347055c26cb0
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.7/src/global.rs:178
  74:     0x559a4423b88c - tokio_threadpool::worker::Worker::do_run::{{closure}}::h17bed53de26e2c67
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:125
  75:     0x559a44240a79 - std::thread::local::LocalKey<T>::try_with::he2baa605067223e0
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:299
  76:     0x559a4423f9ed - std::thread::local::LocalKey<T>::with::hf9f738c51711e3fc
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/local.rs:245
  77:     0x559a4423b6b7 - tokio_threadpool::worker::Worker::do_run::hcaa1d68e8009331b
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/worker/mod.rs:116
  78:     0x559a442465f4 - tokio_threadpool::pool::Pool::spawn_thread::{{closure}}::h4ea2fa66d59bbab1
                               at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-threadpool-0.1.13/src/pool/mod.rs:344
  79:     0x559a4423f3ad - std::sys_common::backtrace::__rust_begin_short_backtrace::h98d3fa8874184d40
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/sys_common/backtrace.rs:136
  80:     0x559a4422a961 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::hd5b54fe29de87b5c
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/mod.rs:469
  81:     0x559a4421bb41 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb1be92189b8f2f15
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panic.rs:309
  82:     0x559a4421c83b - std::panicking::try::do_call::hdcf9cfa3f99fd29a
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panicking.rs:293
  83:     0x559a4471c3f9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  84:     0x559a4421c6a5 - std::panicking::try::hebc24eb33544cf93
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panicking.rs:272
  85:     0x559a4421c491 - std::panic::catch_unwind::h19ed615c3e6d78df
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/panic.rs:388
  86:     0x559a4422a745 - std::thread::Builder::spawn_unchecked::{{closure}}::h544d0ade5684c91f
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/libstd/thread/mod.rs:468
  87:     0x559a4422ccb2 - <F as alloc::boxed::FnBox<A>>::call_box::h9461159cf4914d21
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/liballoc/boxed.rs:749
  88:     0x559a4471b81d - std::sys::unix::thread::Thread::new::thread_start::h20b9f15b8b6ad9bd
                               at /rustc/3eb4890dfe6db0279fdd3cda19f9643873ae3db9/src/liballoc/boxed.rs:759
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:80
  89:     0x7fa7f61214a3 - start_thread
  90:     0x7fa7f5c4cd0e - __clone
  91:                0x0 - <unknown>
```

</p></details>

**Comment by tikue** [comment]
Thanks! This looks like a panic in the tokio runtime. Do you mind hiking against the tokio repo too?

**Comment by tikue** [comment]
Looks like a call to `fuse()` was missing.

**Comment by tikue** [comment]
I've published a new version of tarpc-lib, so I believe a `cargo update` should pick it up.

I haven't updated to the latest changes in nightly yet. I'll do that this week!

**Comment by d1vyank** [comment]
Thank you for the support and the awesome library!
