### ISSUE TITLE
Unclear how to use FutureService correctly in multi-threaded context

### ISSUE THREAD

**Issue by jonhoo** [google/tarpc#84]
As previously discussed in #56, finer grained control over how work is distributed to multiple cores is useful. `FutureService` tries to cater to that, but I have not yet been able to make it work when using multiple threads.

In particular, I run the following code, which I believe is how `FutureService` should be run with multiple threads(?)
```rust
let s = Server;
let addr = "localhost:7000".first_socket_addr();
for _ in 0..4 {
    let s = s.clone();
    thread::spawn(move || {
        let mut core = reactor::Core::new().unwrap();
        let lf = s.listen(addr, Options::default().handle(core.handle()));
        core.run(lf).unwrap();
    });
}

loop {}
```

When run, three of the four threads crash with an "Address already in use" error:
```console
$ rustup run nightly cargo run
   Compiling test v0.1.0 (file:///home/jon/tmp/tarpc-multi)
    Finished dev [unoptimized + debuginfo] target(s) in 4.86 secs
     Running `target/debug/main`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address alreadyin use" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address alreadyin use" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 98, message: "Address alreadyin use" } }', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
```

@tikue claimed in #56 that

> Tarpc configures listeners to allow the reuse of ports, so it should work.

But this seems counter to the behavior I observe above. Am I using the API incorrectly?

<details>
<summary>Click for full program</summary>

```toml
[package]
name = "test"
version = "0.1.0"

[dependencies]
futures = "0.1.9"
tokio-core = "0.1"
tarpc = {git="https://github.com/google/tarpc.git"}
tarpc-plugins = {git = "https://github.com/google/tarpc"}

[[bin]]
name = "main"
path = "src/main.rs"
```
```rust
// src/main.rs
#![feature(conservative_impl_trait, plugin)]
#![plugin(tarpc_plugins)]

#[macro_use]
extern crate tarpc;
extern crate futures;
extern crate tokio_core;

use tarpc::util::Never;
use tokio_core::reactor;
use tarpc::util::FirstSocketAddr;
use std::thread;
use tarpc::server::Options;

pub mod ext {
    service! { rpc foo() -> (); }
}

use self::ext::*;

#[derive(Clone)]
struct Server;

impl ext::FutureService for Server {
    type FooFut = futures::Finished<(), Never>;
    fn foo(&self) -> Self::FooFut {
        futures::finished(())
    }
}

fn main() {
let s = Server;
let addr = "localhost:7000".first_socket_addr();
for _ in 0..4 {
    let s = s.clone();
    thread::spawn(move || {
        let mut core = reactor::Core::new().unwrap();
        let lf = s.listen(addr, Options::default().handle(core.handle()));
        core.run(lf).unwrap();
    });
}

loop {}
}
```
</details>

**Comment by tikue** [comment]
This should work. Definitely an issue.

**Comment by tikue** [comment]
Also, thank you for the very detailed description! It made it very easy to reproduce.
